# If you want to build and run the image yourself, you can use this compose file.

services:
  rozsdhabot:
    build: .
    restart: unless-stopped
    environment:
      # separated by commas, case insensitive.
      # Currently supported: terminal, telegram
      INTEGRATIONS: terminal,telegram

      # If telegram integration is enabled this is required.
      # this token is just an example, you need to get your own.
      TELEGRAM_TOKEN: 123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ

      # If discord integration is enabled this is required.
      DISCORD_TOKEN:

      DISABLE_SAVING: false # set to true to disable saving to and loading from disk
      RUST_LOG: info # available levels: trace, debug, info, warn, error. info is recommended.
    volumes:
      - ./data:/rozsdhabot/data
